# ─────────────────────────────────────────────────────────────────────────────
# terraform/aws/rds.tf — RDS MySQL (shared rca_db)
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_db_subnet_group" "main" {
  name       = "banking-app-db-subnet-group"
  subnet_ids = aws_subnet.public[*].id

  tags = { Name = "banking-app-db-subnet-group" }
}

resource "aws_db_instance" "rca_db" {
  identifier        = "banking-app-rca-db"
  engine            = "mysql"
  engine_version    = "8.0"
  instance_class    = var.rds_instance_class
  allocated_storage = var.rds_allocated_storage_gb
  storage_type      = "gp3"
  storage_encrypted = true

  db_name  = var.rds_db_name
  username = var.rds_username
  # Password is auto-generated by random_password.rds_master (see secrets.tf).
  # Terraform manages the full lifecycle — no manual password step required.
  # The same value is stored in SSM (/banking-app/.../rds-password) for ops access
  # and embedded in the database-url SSM parameter used by ECS tasks.
  password = random_password.rds_master.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  # Backups — keep 7 days in production
  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "Mon:04:00-Mon:05:00"

  # Prevent accidental deletion
  deletion_protection = false # set to true after initial testing

  # Don't take a final snapshot on destroy (speeds up tear-down in dev)
  skip_final_snapshot = true

  tags = { Name = "banking-app-rca-db" }

}

