# ─────────────────────────────────────────────────────────────────────────────
# terraform/aws/secrets.tf — SSM Parameter Store (SecureString)
#
# SSM standard parameters are FREE; Secrets Manager charges $0.40/secret/month.
#
# Password strategy:
#   rds-password  — auto-generated by random_password.rds_master (Terraform-managed,
#                   no manual step required)
#   database-url  — full MySQL URL constructed by Terraform after RDS is created
#                   (Terraform-managed, no manual step required)
#   everything else — placeholder created by Terraform; overwrite after apply:
#
#     aws ssm put-parameter \
#       --name "/banking-app/production/<param>" \
#       --value "<real-value>" --type SecureString --overwrite
#
# Params to set manually after apply:
#   anthropic-api-key, github-pat, gemini-api-key, dd-api-key, dd-app-key
# ─────────────────────────────────────────────────────────────────────────────

locals {
  secret_prefix = "banking-app/${var.environment}"
}

# ── Auto-generated RDS master password ────────────────────────────────────────
# Alphanumeric only — avoids URL-encoding issues when embedded in DATABASE_URL.
# Terraform generates this once on first apply and stores it in state.
resource "random_password" "rds_master" {
  length  = 32
  special = false
}

# ── Database secrets (Terraform-managed, no manual step needed) ───────────────

resource "aws_ssm_parameter" "rds_password" {
  name        = "/${local.secret_prefix}/rds-password"
  description = "RDS MySQL master password (auto-generated by Terraform)"
  type        = "SecureString"
  value       = random_password.rds_master.result
  # No ignore_changes — Terraform is the source of truth for this value.
}

# Full DATABASE_URL constructed from the RDS endpoint + random password.
# ECS tasks inject this as the DATABASE_URL env var via secrets[].
# This parameter is created after RDS, so the hostname is always correct.
resource "aws_ssm_parameter" "database_url" {
  name        = "/${local.secret_prefix}/database-url"
  description = "Full MySQL connection URL for rca-agent and ingestion-agent"
  type        = "SecureString"
  value       = "mysql+pymysql://${var.rds_username}:${random_password.rds_master.result}@${aws_db_instance.rca_db.address}:3306/${var.rds_db_name}"
  # No ignore_changes — Terraform updates this if the RDS endpoint changes.
  depends_on  = [aws_db_instance.rca_db]
}

# ── External-service credentials (set manually after terraform apply) ─────────

resource "aws_ssm_parameter" "anthropic_api_key" {
  name        = "/${local.secret_prefix}/anthropic-api-key"
  description = "Anthropic Claude API key for rca-agent"
  type        = "SecureString"
  value       = "REPLACE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "github_pat" {
  name        = "/${local.secret_prefix}/github-pat"
  description = "GitHub Personal Access Token (repo:read) for rca-agent"
  type        = "SecureString"
  value       = "REPLACE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "gemini_api_key" {
  name        = "/${local.secret_prefix}/gemini-api-key"
  description = "Google Gemini API key for error-ingestion-agent (analyze node)"
  type        = "SecureString"
  value       = "REPLACE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "dd_api_key" {
  name        = "/${local.secret_prefix}/dd-api-key"
  description = "Datadog API key for ingestion-agent and dd-agent sidecar"
  type        = "SecureString"
  value       = "REPLACE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "dd_app_key" {
  name        = "/${local.secret_prefix}/dd-app-key"
  description = "Datadog Application key for ingestion-agent Logs API polling"
  type        = "SecureString"
  value       = "REPLACE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}
