"""
Pre-crafted demo error log payloads for the RCA agent demo.

Fixed UUIDs make /demo/seed idempotent via INSERT IGNORE.
Stack traces mirror actual Java source line numbers so Claude finds the code.
"""

SCENARIO_SINGLE_SERVICE = {
    "id": "demobugb-1111-1111-1111-111111111111",
    "service_name": "order-service",
    "environment": "production",
    "error_type": "IllegalArgumentException",
    "error_message": "Order quantity 0 is invalid",
    "stack_trace": [
        {
            "file": "com/demo/order/service/OrderService.java",
            "line": 111,
            "function": "resolveQuantity",
            "text": 'throw new IllegalArgumentException("Order quantity " + resolved + " is invalid");',
        },
        {
            "file": "com/demo/order/service/OrderService.java",
            "line": 52,
            "function": "createOrder",
            "text": "int resolvedQty = resolveQuantity(req.getQuantity());",
        },
        {
            "file": "com/demo/order/controller/OrderController.java",
            "line": 40,
            "function": "createOrder",
            "text": "OrderDto.Response response = orderService.createOrder(request);",
        },
    ],
    "severity": "high",
    "metadata": {
        "customerId": "CHAOS-CUSTOMER",
        "sku": "SKU-002",
        "quantity": 1,
        "customerTier": "standard",
        "commit": "d3adb33f",
        "chaos_trigger": "quantity-off-by-one",
    },
}

SCENARIO_CROSS_SERVICE = {
    "id": "demobuga-2222-2222-2222-222222222222",
    "service_name": "order-service",
    "environment": "production",
    "error_type": "NullPointerException",
    "error_message": (
        'Cannot invoke "java.lang.Double.doubleValue()" because the return value '
        'of "com.demo.order.dto.PricingResponseDto.getDiscount()" is null'
    ),
    "stack_trace": [
        {
            "file": "com/demo/order/service/OrderService.java",
            "line": 138,
            "function": "calculateTotal",
            "text": "double discountedUnit = unitPrice * (1.0 - discount.doubleValue());",
        },
        {
            "file": "com/demo/order/service/OrderService.java",
            "line": 58,
            "function": "createOrder",
            "text": "double totalPrice = calculateTotal(pricing.getBasePrice(), pricing.getDiscount(), resolvedQty);",
        },
        {
            "file": "com/demo/order/controller/OrderController.java",
            "line": 40,
            "function": "createOrder",
            "text": "OrderDto.Response response = orderService.createOrder(request);",
        },
    ],
    "severity": "critical",
    "metadata": {
        "customerId": "CHAOS-CUSTOMER",
        "sku": "SKU-001",
        "quantity": 2,
        "customerTier": "premium",
        "upstream_service": "pricing-service",
        "upstream_version": "2.1.0",
        "chaos_trigger": "cross-service-npe",
    },
}

SCENARIO_KEY: dict[str, dict] = {
    "single_service": SCENARIO_SINGLE_SERVICE,
    "cross_service": SCENARIO_CROSS_SERVICE,
}

DEMO_SERVICE_REPO_MAP = [
    ("order-service",   "oscorpAI", "order-service",   "main", "Java"),
    ("pricing-service", "oscorpAI", "pricing-service", "main", "Java"),
    ("banking-app",     "oscorpAI", "banking-app",     "main", "Java"),
]


# ── Edit-mode fix definitions ────────────────────────────────────────────────
# Each scenario maps to: target repo, branch prefix, PR copy, and a list of
# deterministic find/replace edits.  Used by rca_agent/fix_creator.py to open
# a real GitHub PR in Edit mode.
#
# `find` strings must match exactly (whitespace included) — verify against the
# source files when changing.
SCENARIO_FIXES: dict[str, dict] = {
    "single_service": {
        "branch_prefix": "claude-rca-fix-bug-b",
        "pr_title": "Fix off-by-one in OrderService.resolveQuantity",
        "pr_body": (
            "## Summary\n"
            "Removes the spurious `- 1` introduced in commit d3adb33f that "
            "converted user-facing 1-indexed quantities to 0-indexed for an "
            "inventory system that is itself 1-indexed.\n\n"
            "## Root cause\n"
            "`quantity=1` → `resolved=0` → `IllegalArgumentException` thrown "
            "from `resolveQuantity`.\n\n"
            "🤖 Generated by Claude RCA Agent — see linked incident report."
        ),
        "repo": "order-service-java",
        "edits": [
            {
                "path": "src/main/java/com/demo/order/service/OrderService.java",
                "find": "        int resolved = quantity - 1;   // ← off-by-one; should be: int resolved = quantity;   // ← off-by-one; should be: int resolved = quantity;",
                "replace": "        int resolved = quantity;",
            },
        ],
    },
    "cross_service": {
        "branch_prefix": "claude-rca-fix-bug-a",
        "pr_title": "Align PricingResponseDto with pricing-service v2.1.0 (discountRate)",
        "pr_body": (
            "## Summary\n"
            "pricing-service v2.1.0 (commit abc1234f) renamed the JSON response "
            "field `discount` → `discountRate`. This PR updates "
            "`PricingResponseDto` and the two callers in `OrderService` so the "
            "field is no longer null.\n\n"
            "## Root cause\n"
            "`PricingResponseDto.getDiscount()` returned null because Jackson "
            "could not bind the renamed upstream field, which threw a "
            "`NullPointerException` in `OrderService.calculateTotal`.\n\n"
            "🤖 Generated by Claude RCA Agent — see linked incident report."
        ),
        "repo": "order-service-java",
        "edits": [
            {
                "path": "src/main/java/com/demo/order/dto/PricingResponseDto.java",
                "find": "    private Double discount;    // ← stale field name; should be 'discountRate'",
                "replace": "    private Double discountRate;",
            },
            {
                "path": "src/main/java/com/demo/order/service/OrderService.java",
                "find": "            double totalPrice = calculateTotal(pricing.getBasePrice(), pricing.getDiscount(), resolvedQty);",
                "replace": "            double totalPrice = calculateTotal(pricing.getBasePrice(), pricing.getDiscountRate(), resolvedQty);",
            },
            {
                "path": "src/main/java/com/demo/order/service/OrderService.java",
                "find": "                    .discountApplied(pricing.getDiscount() != null ? pricing.getDiscount() : 0.0)",
                "replace": "                    .discountApplied(pricing.getDiscountRate() != null ? pricing.getDiscountRate() : 0.0)",
            },
        ],
    },
}
